parameters:
  scenario.messenger.consumer_attempts: 5

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Stateforge\Scenario\Core\PHPUnit\Configuration\ConfigFinder: ~
  Stateforge\Scenario\Core\PHPUnit\Configuration\Configured: ~

  Stateforge\Scenario\Core\PHPUnit\Configuration\ConfiguredInterface:
    alias: Stateforge\Scenario\Core\PHPUnit\Configuration\Configured

  Stateforge\Scenario\Symfony\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/**/Tests/'

  Stateforge\Scenario\Core\Contract\DatabaseRefreshExecutorInterface:
    alias: Stateforge\Scenario\Symfony\Runtime\DatabaseRefreshExecutor
    public: true

  Stateforge\Scenario\Symfony\Runtime\CommandRunnerInterface:
    alias: Stateforge\Scenario\Symfony\Runtime\CommandRunner

  Stateforge\Scenario\Symfony\Runtime\ConfigResolverInterface:
    alias: Stateforge\Scenario\Symfony\Runtime\ConfigResolver

  Stateforge\Scenario\Symfony\Runtime\Messenger\MessageConsumerInterface:
    alias: Stateforge\Scenario\Symfony\Runtime\Messenger\MessageConsumer

  Stateforge\Scenario\Symfony\Runtime\Messenger\MessageConsumer:
    arguments:
      $maxAttempts: '%scenario.messenger.consumer_attempts%'

  Stateforge\Scenario\Symfony\Runtime\Messenger\MessageCounterInterface:
    alias: Stateforge\Scenario\Symfony\Runtime\Messenger\MessageCounter

  Stateforge\Scenario\Symfony\Runtime\Process\ProcessRunnerInterface:
    alias: Stateforge\Scenario\Symfony\Runtime\Process\ProcessRunner

  Stateforge\Scenario\Symfony\Runtime\Metadata\Process\ProcessFactoryInterface:
    alias: Stateforge\Scenario\Symfony\Metadata\Process\ProcessFactory

  _instanceof:
    Stateforge\Scenario\Symfony\Command\ScenarioCommand:
      calls:
        - method: setAllowedEnvs
          arguments:
            - '%scenario.allowed_envs%'
