services:
  _defaults:
    autowire: true
    autoconfigure: true

  Scenario\Symfony\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/**/Tests/'

  Scenario\Symfony\Runtime\CommandRunnerInterface:
    alias: Scenario\Symfony\Runtime\CommandRunner

  Scenario\Symfony\Runtime\ConfigResolverInterface:
    alias: Scenario\Symfony\Runtime\ConfigResolver

  Scenario\Symfony\Runtime\MessageConsumerInterface:
    alias: Scenario\Symfony\Runtime\MessageConsumer

  Scenario\Symfony\Runtime\ProcessRunnerInterface:
    alias: Scenario\Symfony\Runtime\ProcessRunner

  _instanceof:
    Scenario\Symfony\Command\ScenarioCommand:
      calls:
        - method: setAllowedEnvs
          arguments:
            - '%scenario.allowed_envs%'